require "faker"
require "date"
require "csv"

# we already provide a filled out works_seeds.csv file, but feel free to
# run this script in order to replace it and generate a new one
# run using the command:
# $ ruby db/generate_seeds.rb
# if satisfied with this new works_seeds.csv file, recreate the db with:
# $ rails db:reset
# doesn't currently check for if titles are unique against each other

CSV.open("db/works_seeds.csv", "w", :write_headers => true,
                                    :headers => ["category", "title", "creator", "publication_year", "description"]) do |csv|
  works = [
      {category: "Book",
       title: "1Q84",
       creator: "Haruki Murakami",
       publication_year: 2009,
       discription: "very weird and cool dystopian book",
      },
      {category: "Album",
       title: "Currents",
       creator: "Tame Impala",
       publication_year: 2015,
       discription: "A classic. 3rd studio album",
      },
      {category: "Show",
       title: "Bob's Burgers",
       creator: "Loren Bouchard",
       publication_year: 2015,
       discription: "A wholesome comedy that will always cheer you up and has great voice actors",
      },
      {category: "Movie",
       title: "Skeleton Twins",
       creator: "Kristen Wiig",
       publication_year: 2014,
       discription: "depression city",
      },
      {category: "Book",
       title: "Siren of Titans",
       creator: "Kurt Vonnegut",
       publication_year: 1959,
       discription: "a cool space book that's weird and depressing",
      },
      {category: "Book",
       title: "1Q84",
       creator: "Haruki Murakami",
       publication_year: 2009,
       discription: "very weird and cool dystopian book",
      },
      {category: "Album",
       title: "Plans",
       creator: "Death Cab For Cutie",
       publication_year: 2005,
       discription: "A true classic. What a masterpiece.",
      },
      {category: "Show",
       title: "Pen15",
       creator: "Maya Erskine, Anna Konkle",
       publication_year: 2019,
       discription: "being awkward in middle school in 2000",
      },
      {category: "Movie",
       title: "What We Do in the Shadows",
       creator: "Jemaine Clement, Taika Waititi",
       publication_year: 2014,
       discription: "vampires navigating being roommates and friends. comedy gold.",
      },
      {category: "Book",
       title: "Hard-Boiled Wonderland and the End of the World",
       creator: "Haruki Murakami",
       publication_year: 1985,
       discription: "dystopian, parallel realities, a real treat",
      },
      {category: "Album",
       title: "Room on Fire",
       creator: "The Strokes",
       publication_year: 2003,
       discription: "Reptilia is on this album",
      },
      {category: "Show",
       title: "The office",
       creator: "Greg Daniels",
       publication_year: 2005,
       discription: "Steve Carrell. What a guy",
      },
      {category: "Movie",
       title: "The Big Sick",
       creator: "Kumail Nanjiani",
       publication_year: 2017,
       discription: "Kumail Nanjiani at his best. I've seen this a hundred times",
      },
      {category: "",
          title: "",
          creator: "",
          publication_year: ,
          discription: "",
      },
      {category: "",
       title: "",
       creator: "",
       publication_year: ,
       discription: "",
      },
      {category: "",
       title: "",
       creator: "",
       publication_year: ,
       discription: "",
      },
      {category: "",
       title: "",
       creator: "",
       publication_year: ,
       discription: "",
      },
      {category: "",
       title: "",
       creator: "",
       publication_year: ,
       discription: "",
      },
      {category: "",
       title: "",
       creator: "",
       publication_year: ,
       discription: "",
      },
      {category: "",
       title: "",
       creator: "",
       publication_year: ,
       discription: "",
      },
      {category: "",
       title: "",
       creator: "",
       publication_year: ,
       discription: "",
      },
      {category: "",
       title: "",
       creator: "",
       publication_year: ,
       discription: "",
      },
      {category: "",
       title: "",
       creator: "",
       publication_year: ,
       discription: "",
      },
      {category: "",
       title: "",
       creator: "",
       publication_year: ,
       discription: "",
      },
      {category: "",
       title: "",
       creator: "",
       publication_year: ,
       discription: "",
      },

  ]





end
#   25.times do
#     category = %w(album book).sample
#     title = Faker::Coffee.blend_name
#     creator = Faker::Name.name
#     publication_year = rand(Date.today.year - 100..Date.today.year)
#     description = Faker::Lorem.sentence
#
#     csv << [category, title, creator, publication_year, description]
#   end
# end
